/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphGeoCoordinates struct for MicrosoftGraphGeoCoordinates
type MicrosoftGraphGeoCoordinates struct {
	Altitude  interface{} `json:"altitude,omitempty"`
	Latitude  interface{} `json:"latitude,omitempty"`
	Longitude interface{} `json:"longitude,omitempty"`
}
