/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

import (
	"time"
)

// AppRoleAssignment Represents an Azure Active Directory object. The directoryObject type is the base type for many other directory entity types.
type AppRoleAssignment struct {
	AppRoleId            string    `json:"appRoleId,omitempty"`
	CreatedDateTime      time.Time `json:"createdDateTime,omitempty"`
	PrincipalDisplayName string    `json:"principalDisplayName,omitempty"`
	PrincipalId          string    `json:"principalId,omitempty"`
	PrincipalType        string    `json:"principalType,omitempty"`
	ResourceDisplayName  string    `json:"resourceDisplayName,omitempty"`
	ResourceId           string    `json:"resourceId,omitempty"`
}
