/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// CollectionOfDeviceCompliancePolicyState struct for CollectionOfDeviceCompliancePolicyState
type CollectionOfDeviceCompliancePolicyState struct {
	Value []MicrosoftGraphDeviceCompliancePolicyState `json:"value,omitempty"`
}
