/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphAlternativeSecurityId struct for MicrosoftGraphAlternativeSecurityId
type MicrosoftGraphAlternativeSecurityId struct {
	IdentityProvider string `json:"identityProvider,omitempty"`
	Key              string `json:"key,omitempty"`
	Type             int32  `json:"type,omitempty"`
}
