/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1131 struct for InlineObject1131
type InlineObject1131 struct {
	Text     interface{} `json:"text,omitempty"`
	StartNum interface{} `json:"startNum,omitempty"`
	NumBytes interface{} `json:"numBytes,omitempty"`
}
