/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// CollectionOfWindowsInformationProtectionNetworkLearningSummary struct for CollectionOfWindowsInformationProtectionNetworkLearningSummary
type CollectionOfWindowsInformationProtectionNetworkLearningSummary struct {
	Value []MicrosoftGraphWindowsInformationProtectionNetworkLearningSummary `json:"value,omitempty"`
}
