/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1198 struct for InlineObject1198
type InlineObject1198 struct {
	Array interface{} `json:"array,omitempty"`
}
