/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject131 struct for InlineObject131
type InlineObject131 struct {
	ProposedNewTime interface{} `json:"ProposedNewTime,omitempty"`
	SendResponse    bool        `json:"SendResponse,omitempty"`
	Comment         string      `json:"Comment,omitempty"`
}
