/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

import (
	"time"
)

// MicrosoftGraphDrive struct for MicrosoftGraphDrive
type MicrosoftGraphDrive struct {
	Id                   string                    `json:"id,omitempty"`
	CreatedBy            interface{}               `json:"createdBy,omitempty"`
	CreatedDateTime      time.Time                 `json:"createdDateTime,omitempty"`
	Description          string                    `json:"description,omitempty"`
	ETag                 string                    `json:"eTag,omitempty"`
	LastModifiedBy       interface{}               `json:"lastModifiedBy,omitempty"`
	LastModifiedDateTime time.Time                 `json:"lastModifiedDateTime,omitempty"`
	Name                 string                    `json:"name,omitempty"`
	ParentReference      interface{}               `json:"parentReference,omitempty"`
	WebUrl               string                    `json:"webUrl,omitempty"`
	CreatedByUser        interface{}               `json:"createdByUser,omitempty"`
	LastModifiedByUser   interface{}               `json:"lastModifiedByUser,omitempty"`
	DriveType            string                    `json:"driveType,omitempty"`
	Owner                interface{}               `json:"owner,omitempty"`
	Quota                interface{}               `json:"quota,omitempty"`
	SharePointIds        interface{}               `json:"sharePointIds,omitempty"`
	System               interface{}               `json:"system,omitempty"`
	Following            []MicrosoftGraphDriveItem `json:"following,omitempty"`
	Items                []MicrosoftGraphDriveItem `json:"items,omitempty"`
	List                 interface{}               `json:"list,omitempty"`
	Root                 interface{}               `json:"root,omitempty"`
	Special              []MicrosoftGraphDriveItem `json:"special,omitempty"`
}
