/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphTeamsAsyncOperationStatus the model 'MicrosoftGraphTeamsAsyncOperationStatus'
type MicrosoftGraphTeamsAsyncOperationStatus string

// List of microsoft.graph.teamsAsyncOperationStatus
const (
	MICROSOFTGRAPHTEAMSASYNCOPERATIONSTATUS_INVALID              MicrosoftGraphTeamsAsyncOperationStatus = "invalid"
	MICROSOFTGRAPHTEAMSASYNCOPERATIONSTATUS_NOT_STARTED          MicrosoftGraphTeamsAsyncOperationStatus = "notStarted"
	MICROSOFTGRAPHTEAMSASYNCOPERATIONSTATUS_IN_PROGRESS          MicrosoftGraphTeamsAsyncOperationStatus = "inProgress"
	MICROSOFTGRAPHTEAMSASYNCOPERATIONSTATUS_SUCCEEDED            MicrosoftGraphTeamsAsyncOperationStatus = "succeeded"
	MICROSOFTGRAPHTEAMSASYNCOPERATIONSTATUS_FAILED               MicrosoftGraphTeamsAsyncOperationStatus = "failed"
	MICROSOFTGRAPHTEAMSASYNCOPERATIONSTATUS_UNKNOWN_FUTURE_VALUE MicrosoftGraphTeamsAsyncOperationStatus = "unknownFutureValue"
)
