/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

import (
	"time"
)

// MicrosoftGraphNetworkConnection struct for MicrosoftGraphNetworkConnection
type MicrosoftGraphNetworkConnection struct {
	ApplicationName          string      `json:"applicationName,omitempty"`
	DestinationAddress       string      `json:"destinationAddress,omitempty"`
	DestinationDomain        string      `json:"destinationDomain,omitempty"`
	DestinationLocation      string      `json:"destinationLocation,omitempty"`
	DestinationPort          string      `json:"destinationPort,omitempty"`
	DestinationUrl           string      `json:"destinationUrl,omitempty"`
	Direction                interface{} `json:"direction,omitempty"`
	DomainRegisteredDateTime time.Time   `json:"domainRegisteredDateTime,omitempty"`
	LocalDnsName             string      `json:"localDnsName,omitempty"`
	NatDestinationAddress    string      `json:"natDestinationAddress,omitempty"`
	NatDestinationPort       string      `json:"natDestinationPort,omitempty"`
	NatSourceAddress         string      `json:"natSourceAddress,omitempty"`
	NatSourcePort            string      `json:"natSourcePort,omitempty"`
	Protocol                 interface{} `json:"protocol,omitempty"`
	RiskScore                string      `json:"riskScore,omitempty"`
	SourceAddress            string      `json:"sourceAddress,omitempty"`
	SourceLocation           string      `json:"sourceLocation,omitempty"`
	SourcePort               string      `json:"sourcePort,omitempty"`
	Status                   interface{} `json:"status,omitempty"`
	UrlParameters            string      `json:"urlParameters,omitempty"`
}
