/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// WorkbookTableRow struct for WorkbookTableRow
type WorkbookTableRow struct {
	Index  int32       `json:"index,omitempty"`
	Values interface{} `json:"values,omitempty"`
}
