/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// ColumnDefinition struct for ColumnDefinition
type ColumnDefinition struct {
	Boolean             interface{} `json:"boolean,omitempty"`
	Calculated          interface{} `json:"calculated,omitempty"`
	Choice              interface{} `json:"choice,omitempty"`
	ColumnGroup         string      `json:"columnGroup,omitempty"`
	Currency            interface{} `json:"currency,omitempty"`
	DateTime            interface{} `json:"dateTime,omitempty"`
	DefaultValue        interface{} `json:"defaultValue,omitempty"`
	Description         string      `json:"description,omitempty"`
	DisplayName         string      `json:"displayName,omitempty"`
	EnforceUniqueValues bool        `json:"enforceUniqueValues,omitempty"`
	Geolocation         interface{} `json:"geolocation,omitempty"`
	Hidden              bool        `json:"hidden,omitempty"`
	Indexed             bool        `json:"indexed,omitempty"`
	Lookup              interface{} `json:"lookup,omitempty"`
	Name                string      `json:"name,omitempty"`
	Number              interface{} `json:"number,omitempty"`
	PersonOrGroup       interface{} `json:"personOrGroup,omitempty"`
	ReadOnly            bool        `json:"readOnly,omitempty"`
	Required            bool        `json:"required,omitempty"`
	Text                interface{} `json:"text,omitempty"`
}
