/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject991 struct for InlineObject991
type InlineObject991 struct {
	DateText interface{} `json:"dateText,omitempty"`
}
