/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

import (
	"time"
)

// MicrosoftGraphDomainState struct for MicrosoftGraphDomainState
type MicrosoftGraphDomainState struct {
	LastActionDateTime time.Time `json:"lastActionDateTime,omitempty"`
	Operation          string    `json:"operation,omitempty"`
	Status             string    `json:"status,omitempty"`
}
