/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphEducationSchool struct for MicrosoftGraphEducationSchool
type MicrosoftGraphEducationSchool struct {
	Id                  string                         `json:"id,omitempty"`
	Description         string                         `json:"description,omitempty"`
	DisplayName         string                         `json:"displayName,omitempty"`
	ExternalSource      interface{}                    `json:"externalSource,omitempty"`
	Address             interface{}                    `json:"address,omitempty"`
	CreatedBy           interface{}                    `json:"createdBy,omitempty"`
	ExternalId          string                         `json:"externalId,omitempty"`
	ExternalPrincipalId string                         `json:"externalPrincipalId,omitempty"`
	Fax                 string                         `json:"fax,omitempty"`
	HighestGrade        string                         `json:"highestGrade,omitempty"`
	LowestGrade         string                         `json:"lowestGrade,omitempty"`
	Phone               string                         `json:"phone,omitempty"`
	PrincipalEmail      string                         `json:"principalEmail,omitempty"`
	PrincipalName       string                         `json:"principalName,omitempty"`
	SchoolNumber        string                         `json:"schoolNumber,omitempty"`
	Classes             []MicrosoftGraphEducationClass `json:"classes,omitempty"`
	Users               []MicrosoftGraphEducationUser  `json:"users,omitempty"`
}
