/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1030 struct for InlineObject1030
type InlineObject1030 struct {
	ErrorVal interface{} `json:"errorVal,omitempty"`
}
