/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject806 struct for InlineObject806
type InlineObject806 struct {
	Id               string `json:"id,omitempty"`
	GroupId          string `json:"groupId,omitempty"`
	SiteCollectionId string `json:"siteCollectionId,omitempty"`
	SiteId           string `json:"siteId,omitempty"`
}
