/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject958 struct for InlineObject958
type InlineObject958 struct {
	Probability interface{} `json:"probability,omitempty"`
	DegFreedom  interface{} `json:"degFreedom,omitempty"`
}
