/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1002 struct for InlineObject1002
type InlineObject1002 struct {
	Number interface{} `json:"number,omitempty"`
	Places interface{} `json:"places,omitempty"`
}
