/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject984 struct for InlineObject984
type InlineObject984 struct {
	Settlement interface{} `json:"settlement,omitempty"`
	Maturity   interface{} `json:"maturity,omitempty"`
	Frequency  interface{} `json:"frequency,omitempty"`
	Basis      interface{} `json:"basis,omitempty"`
}
