/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1292 struct for InlineObject1292
type InlineObject1292 struct {
	Percent int32 `json:"percent,omitempty"`
}
