/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1021 struct for InlineObject1021
type InlineObject1021 struct {
	Database interface{} `json:"database,omitempty"`
	Field    interface{} `json:"field,omitempty"`
	Criteria interface{} `json:"criteria,omitempty"`
}
