/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphAttendeeBase struct for MicrosoftGraphAttendeeBase
type MicrosoftGraphAttendeeBase struct {
	EmailAddress interface{} `json:"emailAddress,omitempty"`
	Type         interface{} `json:"type,omitempty"`
}
