/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1194 struct for InlineObject1194
type InlineObject1194 struct {
	Number interface{} `json:"number,omitempty"`
	Form   interface{} `json:"form,omitempty"`
}
