/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// OutlookCategory struct for OutlookCategory
type OutlookCategory struct {
	Color       interface{} `json:"color,omitempty"`
	DisplayName string      `json:"displayName,omitempty"`
}
