/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1326 struct for InlineObject1326
type InlineObject1326 struct {
	Address    string `json:"address,omitempty"`
	HasHeaders bool   `json:"hasHeaders,omitempty"`
}
