/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphMeetingTimeSuggestion struct for MicrosoftGraphMeetingTimeSuggestion
type MicrosoftGraphMeetingTimeSuggestion struct {
	AttendeeAvailability  []interface{} `json:"attendeeAvailability,omitempty"`
	Confidence            interface{}   `json:"confidence,omitempty"`
	Locations             []interface{} `json:"locations,omitempty"`
	MeetingTimeSlot       interface{}   `json:"meetingTimeSlot,omitempty"`
	Order                 int32         `json:"order,omitempty"`
	OrganizerAvailability interface{}   `json:"organizerAvailability,omitempty"`
	SuggestionReason      string        `json:"suggestionReason,omitempty"`
}
