/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1300 struct for InlineObject1300
type InlineObject1300 struct {
	Criteria interface{} `json:"criteria,omitempty"`
}
