/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphPhysicalOfficeAddress struct for MicrosoftGraphPhysicalOfficeAddress
type MicrosoftGraphPhysicalOfficeAddress struct {
	City            string `json:"city,omitempty"`
	CountryOrRegion string `json:"countryOrRegion,omitempty"`
	OfficeLocation  string `json:"officeLocation,omitempty"`
	PostalCode      string `json:"postalCode,omitempty"`
	State           string `json:"state,omitempty"`
	Street          string `json:"street,omitempty"`
}
