/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1046 struct for InlineObject1046
type InlineObject1046 struct {
	Number       interface{} `json:"number,omitempty"`
	Significance interface{} `json:"significance,omitempty"`
	Mode         interface{} `json:"mode,omitempty"`
}
