/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject419 struct for InlineObject419
type InlineObject419 struct {
	InputIds     []string    `json:"InputIds,omitempty"`
	TargetIdType interface{} `json:"TargetIdType,omitempty"`
	SourceIdType interface{} `json:"SourceIdType,omitempty"`
}
