/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphManagementAgentType the model 'MicrosoftGraphManagementAgentType'
type MicrosoftGraphManagementAgentType string

// List of microsoft.graph.managementAgentType
const (
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_EAS                                   MicrosoftGraphManagementAgentType = "eas"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_MDM                                   MicrosoftGraphManagementAgentType = "mdm"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_EAS_MDM                               MicrosoftGraphManagementAgentType = "easMdm"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_INTUNE_CLIENT                         MicrosoftGraphManagementAgentType = "intuneClient"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_EAS_INTUNE_CLIENT                     MicrosoftGraphManagementAgentType = "easIntuneClient"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_CONFIGURATION_MANAGER_CLIENT          MicrosoftGraphManagementAgentType = "configurationManagerClient"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_CONFIGURATION_MANAGER_CLIENT_MDM      MicrosoftGraphManagementAgentType = "configurationManagerClientMdm"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_CONFIGURATION_MANAGER_CLIENT_MDM_EAS  MicrosoftGraphManagementAgentType = "configurationManagerClientMdmEas"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_UNKNOWN                               MicrosoftGraphManagementAgentType = "unknown"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_JAMF                                  MicrosoftGraphManagementAgentType = "jamf"
	MICROSOFTGRAPHMANAGEMENTAGENTTYPE_GOOGLE_CLOUD_DEVICE_POLICY_CONTROLLER MicrosoftGraphManagementAgentType = "googleCloudDevicePolicyController"
)
