/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphGroupType the model 'MicrosoftGraphGroupType'
type MicrosoftGraphGroupType string

// List of microsoft.graph.groupType
const (
	MICROSOFTGRAPHGROUPTYPE_UNIFIED_GROUPS       MicrosoftGraphGroupType = "unifiedGroups"
	MICROSOFTGRAPHGROUPTYPE_AZURE_AD             MicrosoftGraphGroupType = "azureAD"
	MICROSOFTGRAPHGROUPTYPE_UNKNOWN_FUTURE_VALUE MicrosoftGraphGroupType = "unknownFutureValue"
)
