/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject142 struct for InlineObject142
type InlineObject142 struct {
	DisplayName      string `json:"displayName,omitempty"`
	MailNickname     string `json:"mailNickname,omitempty"`
	OnBehalfOfUserId string `json:"onBehalfOfUserId,omitempty"`
}
