/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject741 struct for InlineObject741
type InlineObject741 struct {
	AttachmentItem MicrosoftGraphAttachmentItem `json:"AttachmentItem,omitempty"`
}
