/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject890 struct for InlineObject890
type InlineObject890 struct {
	GroupId          string `json:"groupId,omitempty"`
	RenameAs         string `json:"renameAs,omitempty"`
	NotebookFolder   string `json:"notebookFolder,omitempty"`
	SiteCollectionId string `json:"siteCollectionId,omitempty"`
	SiteId           string `json:"siteId,omitempty"`
}
