/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// SharedDriveItem struct for SharedDriveItem
type SharedDriveItem struct {
	Owner      interface{}               `json:"owner,omitempty"`
	DriveItem  interface{}               `json:"driveItem,omitempty"`
	Items      []MicrosoftGraphDriveItem `json:"items,omitempty"`
	List       interface{}               `json:"list,omitempty"`
	ListItem   interface{}               `json:"listItem,omitempty"`
	Permission interface{}               `json:"permission,omitempty"`
	Root       interface{}               `json:"root,omitempty"`
	Site       interface{}               `json:"site,omitempty"`
}
