/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// WorkbookChartSeries struct for WorkbookChartSeries
type WorkbookChartSeries struct {
	Name   string                             `json:"name,omitempty"`
	Format interface{}                        `json:"format,omitempty"`
	Points []MicrosoftGraphWorkbookChartPoint `json:"points,omitempty"`
}
