/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1024 struct for InlineObject1024
type InlineObject1024 struct {
	NominalRate interface{} `json:"nominalRate,omitempty"`
	Npery       interface{} `json:"npery,omitempty"`
}
