/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// LinkedResource struct for LinkedResource
type LinkedResource struct {
	ApplicationName string `json:"applicationName,omitempty"`
	DisplayName     string `json:"displayName,omitempty"`
	ExternalId      string `json:"externalId,omitempty"`
	WebUrl          string `json:"webUrl,omitempty"`
}
