/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1139 struct for InlineObject1139
type InlineObject1139 struct {
	Values interface{} `json:"values,omitempty"`
}
