/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphInformationProtection struct for MicrosoftGraphInformationProtection
type MicrosoftGraphInformationProtection struct {
	Id                       string                                  `json:"id,omitempty"`
	ThreatAssessmentRequests []MicrosoftGraphThreatAssessmentRequest `json:"threatAssessmentRequests,omitempty"`
}
