/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphDeviceComplianceActionType the model 'MicrosoftGraphDeviceComplianceActionType'
type MicrosoftGraphDeviceComplianceActionType string

// List of microsoft.graph.deviceComplianceActionType
const (
	MICROSOFTGRAPHDEVICECOMPLIANCEACTIONTYPE_NO_ACTION                       MicrosoftGraphDeviceComplianceActionType = "noAction"
	MICROSOFTGRAPHDEVICECOMPLIANCEACTIONTYPE_NOTIFICATION                    MicrosoftGraphDeviceComplianceActionType = "notification"
	MICROSOFTGRAPHDEVICECOMPLIANCEACTIONTYPE_BLOCK                           MicrosoftGraphDeviceComplianceActionType = "block"
	MICROSOFTGRAPHDEVICECOMPLIANCEACTIONTYPE_RETIRE                          MicrosoftGraphDeviceComplianceActionType = "retire"
	MICROSOFTGRAPHDEVICECOMPLIANCEACTIONTYPE_WIPE                            MicrosoftGraphDeviceComplianceActionType = "wipe"
	MICROSOFTGRAPHDEVICECOMPLIANCEACTIONTYPE_REMOVE_RESOURCE_ACCESS_PROFILES MicrosoftGraphDeviceComplianceActionType = "removeResourceAccessProfiles"
	MICROSOFTGRAPHDEVICECOMPLIANCEACTIONTYPE_PUSH_NOTIFICATION               MicrosoftGraphDeviceComplianceActionType = "pushNotification"
)
