/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject112 struct for InlineObject112
type InlineObject112 struct {
	Post MicrosoftGraphPost `json:"Post,omitempty"`
}
