/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphHostSecurityState struct for MicrosoftGraphHostSecurityState
type MicrosoftGraphHostSecurityState struct {
	Fqdn                      string `json:"fqdn,omitempty"`
	IsAzureAdJoined           bool   `json:"isAzureAdJoined,omitempty"`
	IsAzureAdRegistered       bool   `json:"isAzureAdRegistered,omitempty"`
	IsHybridAzureDomainJoined bool   `json:"isHybridAzureDomainJoined,omitempty"`
	NetBiosName               string `json:"netBiosName,omitempty"`
	Os                        string `json:"os,omitempty"`
	PrivateIpAddress          string `json:"privateIpAddress,omitempty"`
	PublicIpAddress           string `json:"publicIpAddress,omitempty"`
	RiskScore                 string `json:"riskScore,omitempty"`
}
