/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject344 struct for InlineObject344
type InlineObject344 struct {
	ToRecipients []interface{} `json:"ToRecipients,omitempty"`
	Comment      string        `json:"Comment,omitempty"`
}
