/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject27 struct for InlineObject27
type InlineObject27 struct {
	Apps []interface{} `json:"apps,omitempty"`
}
