/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject946 struct for InlineObject946
type InlineObject946 struct {
	Trials       interface{} `json:"trials,omitempty"`
	ProbabilityS interface{} `json:"probabilityS,omitempty"`
	NumberS      interface{} `json:"numberS,omitempty"`
	NumberS2     interface{} `json:"numberS2,omitempty"`
}
