/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1172 struct for InlineObject1172
type InlineObject1172 struct {
	Number interface{} `json:"number,omitempty"`
	Power  interface{} `json:"power,omitempty"`
}
