/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphCallRecordsFailureStage the model 'MicrosoftGraphCallRecordsFailureStage'
type MicrosoftGraphCallRecordsFailureStage string

// List of microsoft.graph.callRecords.failureStage
const (
	MICROSOFTGRAPHCALLRECORDSFAILURESTAGE_UNKNOWN              MicrosoftGraphCallRecordsFailureStage = "unknown"
	MICROSOFTGRAPHCALLRECORDSFAILURESTAGE_CALL_SETUP           MicrosoftGraphCallRecordsFailureStage = "callSetup"
	MICROSOFTGRAPHCALLRECORDSFAILURESTAGE_MIDCALL              MicrosoftGraphCallRecordsFailureStage = "midcall"
	MICROSOFTGRAPHCALLRECORDSFAILURESTAGE_UNKNOWN_FUTURE_VALUE MicrosoftGraphCallRecordsFailureStage = "unknownFutureValue"
)
