/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphToneInfo struct for MicrosoftGraphToneInfo
type MicrosoftGraphToneInfo struct {
	SequenceId int64       `json:"sequenceId,omitempty"`
	Tone       interface{} `json:"tone,omitempty"`
}
