/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphManagedAppClipboardSharingLevel the model 'MicrosoftGraphManagedAppClipboardSharingLevel'
type MicrosoftGraphManagedAppClipboardSharingLevel string

// List of microsoft.graph.managedAppClipboardSharingLevel
const (
	MICROSOFTGRAPHMANAGEDAPPCLIPBOARDSHARINGLEVEL_ALL_APPS                   MicrosoftGraphManagedAppClipboardSharingLevel = "allApps"
	MICROSOFTGRAPHMANAGEDAPPCLIPBOARDSHARINGLEVEL_MANAGED_APPS_WITH_PASTE_IN MicrosoftGraphManagedAppClipboardSharingLevel = "managedAppsWithPasteIn"
	MICROSOFTGRAPHMANAGEDAPPCLIPBOARDSHARINGLEVEL_MANAGED_APPS               MicrosoftGraphManagedAppClipboardSharingLevel = "managedApps"
	MICROSOFTGRAPHMANAGEDAPPCLIPBOARDSHARINGLEVEL_BLOCKED                    MicrosoftGraphManagedAppClipboardSharingLevel = "blocked"
)
