/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphSecurityResourceType the model 'MicrosoftGraphSecurityResourceType'
type MicrosoftGraphSecurityResourceType string

// List of microsoft.graph.securityResourceType
const (
	MICROSOFTGRAPHSECURITYRESOURCETYPE_UNKNOWN              MicrosoftGraphSecurityResourceType = "unknown"
	MICROSOFTGRAPHSECURITYRESOURCETYPE_ATTACKED             MicrosoftGraphSecurityResourceType = "attacked"
	MICROSOFTGRAPHSECURITYRESOURCETYPE_RELATED              MicrosoftGraphSecurityResourceType = "related"
	MICROSOFTGRAPHSECURITYRESOURCETYPE_UNKNOWN_FUTURE_VALUE MicrosoftGraphSecurityResourceType = "unknownFutureValue"
)
