/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1019 struct for InlineObject1019
type InlineObject1019 struct {
	Settlement interface{} `json:"settlement,omitempty"`
	Maturity   interface{} `json:"maturity,omitempty"`
	Coupon     interface{} `json:"coupon,omitempty"`
	Yld        interface{} `json:"yld,omitempty"`
	Frequency  interface{} `json:"frequency,omitempty"`
	Basis      interface{} `json:"basis,omitempty"`
}
