/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1267 struct for InlineObject1267
type InlineObject1267 struct {
	Settlement interface{} `json:"settlement,omitempty"`
	Maturity   interface{} `json:"maturity,omitempty"`
	Pr         interface{} `json:"pr,omitempty"`
	Redemption interface{} `json:"redemption,omitempty"`
	Basis      interface{} `json:"basis,omitempty"`
}
