/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1110 struct for InlineObject1110
type InlineObject1110 struct {
	Value interface{} `json:"value,omitempty"`
}
