/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject288 struct for InlineObject288
type InlineObject288 struct {
	NewReminderTime MicrosoftGraphDateTimeTimeZone `json:"NewReminderTime,omitempty"`
}
