/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphManagedAppFlaggedReason the model 'MicrosoftGraphManagedAppFlaggedReason'
type MicrosoftGraphManagedAppFlaggedReason string

// List of microsoft.graph.managedAppFlaggedReason
const (
	MICROSOFTGRAPHMANAGEDAPPFLAGGEDREASON_NONE          MicrosoftGraphManagedAppFlaggedReason = "none"
	MICROSOFTGRAPHMANAGEDAPPFLAGGEDREASON_ROOTED_DEVICE MicrosoftGraphManagedAppFlaggedReason = "rootedDevice"
)
