/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

import (
	"time"
)

// MicrosoftGraphDeviceHealthAttestationState struct for MicrosoftGraphDeviceHealthAttestationState
type MicrosoftGraphDeviceHealthAttestationState struct {
	// TWhen an Attestation Identity Key (AIK) is present on a device, it indicates that the device has an endorsement key (EK) certificate.
	AttestationIdentityKey string `json:"attestationIdentityKey,omitempty"`
	// On or Off of BitLocker Drive Encryption
	BitLockerStatus string `json:"bitLockerStatus,omitempty"`
	// The security version number of the Boot Application
	BootAppSecurityVersion string `json:"bootAppSecurityVersion,omitempty"`
	// When bootDebugging is enabled, the device is used in development and testing
	BootDebugging string `json:"bootDebugging,omitempty"`
	// The security version number of the Boot Application
	BootManagerSecurityVersion string `json:"bootManagerSecurityVersion,omitempty"`
	// The version of the Boot Manager
	BootManagerVersion string `json:"bootManagerVersion,omitempty"`
	// The Boot Revision List that was loaded during initial boot on the attested device
	BootRevisionListInfo string `json:"bootRevisionListInfo,omitempty"`
	//  When code integrity is enabled, code execution is restricted to integrity verified code
	CodeIntegrity string `json:"codeIntegrity,omitempty"`
	// The version of the Boot Manager
	CodeIntegrityCheckVersion string `json:"codeIntegrityCheckVersion,omitempty"`
	// The Code Integrity policy that is controlling the security of the boot environment
	CodeIntegrityPolicy string `json:"codeIntegrityPolicy,omitempty"`
	// The DHA report version. (Namespace version)
	ContentNamespaceUrl string `json:"contentNamespaceUrl,omitempty"`
	// The HealthAttestation state schema version
	ContentVersion string `json:"contentVersion,omitempty"`
	// DEP Policy defines a set of hardware and software technologies that perform additional checks on memory
	DataExcutionPolicy string `json:"dataExcutionPolicy,omitempty"`
	// The DHA report version. (Namespace version)
	DeviceHealthAttestationStatus string `json:"deviceHealthAttestationStatus,omitempty"`
	// ELAM provides protection for the computers in your network when they start up
	EarlyLaunchAntiMalwareDriverProtection string `json:"earlyLaunchAntiMalwareDriverProtection,omitempty"`
	// This attribute indicates if DHA is supported for the device
	HealthAttestationSupportedStatus string `json:"healthAttestationSupportedStatus,omitempty"`
	// This attribute appears if DHA-Service detects an integrity issue
	HealthStatusMismatchInfo string `json:"healthStatusMismatchInfo,omitempty"`
	// The DateTime when device was evaluated or issued to MDM
	IssuedDateTime time.Time `json:"issuedDateTime,omitempty"`
	// The Timestamp of the last update.
	LastUpdateDateTime string `json:"lastUpdateDateTime,omitempty"`
	// When operatingSystemKernelDebugging is enabled, the device is used in development and testing
	OperatingSystemKernelDebugging string `json:"operatingSystemKernelDebugging,omitempty"`
	// The Operating System Revision List that was loaded during initial boot on the attested device
	OperatingSystemRevListInfo string `json:"operatingSystemRevListInfo,omitempty"`
	// The measurement that is captured in PCR[0]
	Pcr0 string `json:"pcr0,omitempty"`
	// Informational attribute that identifies the HASH algorithm that was used by TPM
	PcrHashAlgorithm string `json:"pcrHashAlgorithm,omitempty"`
	// The number of times a PC device has hibernated or resumed
	ResetCount int64 `json:"resetCount,omitempty"`
	// The number of times a PC device has rebooted
	RestartCount int64 `json:"restartCount,omitempty"`
	// Safe mode is a troubleshooting option for Windows that starts your computer in a limited state
	SafeMode string `json:"safeMode,omitempty"`
	// When Secure Boot is enabled, the core components must have the correct cryptographic signatures
	SecureBoot string `json:"secureBoot,omitempty"`
	// Fingerprint of the Custom Secure Boot Configuration Policy
	SecureBootConfigurationPolicyFingerPrint string `json:"secureBootConfigurationPolicyFingerPrint,omitempty"`
	// When test signing is allowed, the device does not enforce signature validation during boot
	TestSigning string `json:"testSigning,omitempty"`
	// The security version number of the Boot Application
	TpmVersion string `json:"tpmVersion,omitempty"`
	// VSM is a container that protects high value assets from a compromised kernel
	VirtualSecureMode string `json:"virtualSecureMode,omitempty"`
	// Operating system running with limited services that is used to prepare a computer for Windows
	WindowsPE string `json:"windowsPE,omitempty"`
}
