/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// OnenoteSection struct for OnenoteSection
type OnenoteSection struct {
	IsDefault          bool                        `json:"isDefault,omitempty"`
	Links              interface{}                 `json:"links,omitempty"`
	PagesUrl           string                      `json:"pagesUrl,omitempty"`
	Pages              []MicrosoftGraphOnenotePage `json:"pages,omitempty"`
	ParentNotebook     interface{}                 `json:"parentNotebook,omitempty"`
	ParentSectionGroup interface{}                 `json:"parentSectionGroup,omitempty"`
}
