/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject919 struct for InlineObject919
type InlineObject919 struct {
	Cost          interface{} `json:"cost,omitempty"`
	DatePurchased interface{} `json:"datePurchased,omitempty"`
	FirstPeriod   interface{} `json:"firstPeriod,omitempty"`
	Salvage       interface{} `json:"salvage,omitempty"`
	Period        interface{} `json:"period,omitempty"`
	Rate          interface{} `json:"rate,omitempty"`
	Basis         interface{} `json:"basis,omitempty"`
}
