/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// CalendarGroup struct for CalendarGroup
type CalendarGroup struct {
	ChangeKey string                   `json:"changeKey,omitempty"`
	ClassId   string                   `json:"classId,omitempty"`
	Name      string                   `json:"name,omitempty"`
	Calendars []MicrosoftGraphCalendar `json:"calendars,omitempty"`
}
