/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphManagedAppDataTransferLevel the model 'MicrosoftGraphManagedAppDataTransferLevel'
type MicrosoftGraphManagedAppDataTransferLevel string

// List of microsoft.graph.managedAppDataTransferLevel
const (
	MICROSOFTGRAPHMANAGEDAPPDATATRANSFERLEVEL_ALL_APPS     MicrosoftGraphManagedAppDataTransferLevel = "allApps"
	MICROSOFTGRAPHMANAGEDAPPDATATRANSFERLEVEL_MANAGED_APPS MicrosoftGraphManagedAppDataTransferLevel = "managedApps"
	MICROSOFTGRAPHMANAGEDAPPDATATRANSFERLEVEL_NONE         MicrosoftGraphManagedAppDataTransferLevel = "none"
)
