/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphChatMessageType the model 'MicrosoftGraphChatMessageType'
type MicrosoftGraphChatMessageType string

// List of microsoft.graph.chatMessageType
const (
	MICROSOFTGRAPHCHATMESSAGETYPE_MESSAGE              MicrosoftGraphChatMessageType = "message"
	MICROSOFTGRAPHCHATMESSAGETYPE_CHAT_EVENT           MicrosoftGraphChatMessageType = "chatEvent"
	MICROSOFTGRAPHCHATMESSAGETYPE_TYPING               MicrosoftGraphChatMessageType = "typing"
	MICROSOFTGRAPHCHATMESSAGETYPE_UNKNOWN_FUTURE_VALUE MicrosoftGraphChatMessageType = "unknownFutureValue"
)
