/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphTimeZoneInformation struct for MicrosoftGraphTimeZoneInformation
type MicrosoftGraphTimeZoneInformation struct {
	Alias       string `json:"alias,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
}
