/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphPhoneType the model 'MicrosoftGraphPhoneType'
type MicrosoftGraphPhoneType string

// List of microsoft.graph.phoneType
const (
	MICROSOFTGRAPHPHONETYPE_HOME         MicrosoftGraphPhoneType = "home"
	MICROSOFTGRAPHPHONETYPE_BUSINESS     MicrosoftGraphPhoneType = "business"
	MICROSOFTGRAPHPHONETYPE_MOBILE       MicrosoftGraphPhoneType = "mobile"
	MICROSOFTGRAPHPHONETYPE_OTHER        MicrosoftGraphPhoneType = "other"
	MICROSOFTGRAPHPHONETYPE_ASSISTANT    MicrosoftGraphPhoneType = "assistant"
	MICROSOFTGRAPHPHONETYPE_HOME_FAX     MicrosoftGraphPhoneType = "homeFax"
	MICROSOFTGRAPHPHONETYPE_BUSINESS_FAX MicrosoftGraphPhoneType = "businessFax"
	MICROSOFTGRAPHPHONETYPE_OTHER_FAX    MicrosoftGraphPhoneType = "otherFax"
	MICROSOFTGRAPHPHONETYPE_PAGER        MicrosoftGraphPhoneType = "pager"
	MICROSOFTGRAPHPHONETYPE_RADIO        MicrosoftGraphPhoneType = "radio"
)
