/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// CollectionOfTokenLifetimePolicy struct for CollectionOfTokenLifetimePolicy
type CollectionOfTokenLifetimePolicy struct {
	Value []MicrosoftGraphTokenLifetimePolicy `json:"value,omitempty"`
}
