/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphItemBody struct for MicrosoftGraphItemBody
type MicrosoftGraphItemBody struct {
	Content     string      `json:"content,omitempty"`
	ContentType interface{} `json:"contentType,omitempty"`
}
