/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphWorkbookIcon struct for MicrosoftGraphWorkbookIcon
type MicrosoftGraphWorkbookIcon struct {
	Index int32  `json:"index,omitempty"`
	Set   string `json:"set,omitempty"`
}
