/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject10 struct for InlineObject10
type InlineObject10 struct {
	Targets     []MicrosoftGraphInvitationParticipantInfo `json:"targets,omitempty"`
	Timeout     int32                                     `json:"timeout,omitempty"`
	CallbackUri string                                    `json:"callbackUri,omitempty"`
}
