/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphApplicationType the model 'MicrosoftGraphApplicationType'
type MicrosoftGraphApplicationType string

// List of microsoft.graph.applicationType
const (
	MICROSOFTGRAPHAPPLICATIONTYPE_UNIVERSAL MicrosoftGraphApplicationType = "universal"
	MICROSOFTGRAPHAPPLICATIONTYPE_DESKTOP   MicrosoftGraphApplicationType = "desktop"
)
