/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphWorkbookChartAxisTitle struct for MicrosoftGraphWorkbookChartAxisTitle
type MicrosoftGraphWorkbookChartAxisTitle struct {
	Id      string      `json:"id,omitempty"`
	Text    string      `json:"text,omitempty"`
	Visible bool        `json:"visible,omitempty"`
	Format  interface{} `json:"format,omitempty"`
}
