/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1347 struct for InlineObject1347
type InlineObject1347 struct {
	Icon interface{} `json:"icon,omitempty"`
}
