/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// CollectionOfDeviceConfiguration struct for CollectionOfDeviceConfiguration
type CollectionOfDeviceConfiguration struct {
	Value []MicrosoftGraphDeviceConfiguration `json:"value,omitempty"`
}
