/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// WorkbookChartSeriesFormat struct for WorkbookChartSeriesFormat
type WorkbookChartSeriesFormat struct {
	Fill interface{} `json:"fill,omitempty"`
	Line interface{} `json:"line,omitempty"`
}
