/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

import (
	"time"
)

// MicrosoftGraphEvent struct for MicrosoftGraphEvent
type MicrosoftGraphEvent struct {
	Id                            string                                            `json:"id,omitempty"`
	Categories                    []string                                          `json:"categories,omitempty"`
	ChangeKey                     string                                            `json:"changeKey,omitempty"`
	CreatedDateTime               time.Time                                         `json:"createdDateTime,omitempty"`
	LastModifiedDateTime          time.Time                                         `json:"lastModifiedDateTime,omitempty"`
	AllowNewTimeProposals         bool                                              `json:"allowNewTimeProposals,omitempty"`
	Attendees                     []interface{}                                     `json:"attendees,omitempty"`
	Body                          interface{}                                       `json:"body,omitempty"`
	BodyPreview                   string                                            `json:"bodyPreview,omitempty"`
	End                           interface{}                                       `json:"end,omitempty"`
	HasAttachments                bool                                              `json:"hasAttachments,omitempty"`
	ICalUId                       string                                            `json:"iCalUId,omitempty"`
	Importance                    interface{}                                       `json:"importance,omitempty"`
	IsAllDay                      bool                                              `json:"isAllDay,omitempty"`
	IsCancelled                   bool                                              `json:"isCancelled,omitempty"`
	IsDraft                       bool                                              `json:"isDraft,omitempty"`
	IsOnlineMeeting               bool                                              `json:"isOnlineMeeting,omitempty"`
	IsOrganizer                   bool                                              `json:"isOrganizer,omitempty"`
	IsReminderOn                  bool                                              `json:"isReminderOn,omitempty"`
	Location                      interface{}                                       `json:"location,omitempty"`
	Locations                     []interface{}                                     `json:"locations,omitempty"`
	OnlineMeeting                 interface{}                                       `json:"onlineMeeting,omitempty"`
	OnlineMeetingProvider         interface{}                                       `json:"onlineMeetingProvider,omitempty"`
	OnlineMeetingUrl              string                                            `json:"onlineMeetingUrl,omitempty"`
	Organizer                     interface{}                                       `json:"organizer,omitempty"`
	OriginalEndTimeZone           string                                            `json:"originalEndTimeZone,omitempty"`
	OriginalStart                 time.Time                                         `json:"originalStart,omitempty"`
	OriginalStartTimeZone         string                                            `json:"originalStartTimeZone,omitempty"`
	Recurrence                    interface{}                                       `json:"recurrence,omitempty"`
	ReminderMinutesBeforeStart    int32                                             `json:"reminderMinutesBeforeStart,omitempty"`
	ResponseRequested             bool                                              `json:"responseRequested,omitempty"`
	ResponseStatus                interface{}                                       `json:"responseStatus,omitempty"`
	Sensitivity                   interface{}                                       `json:"sensitivity,omitempty"`
	SeriesMasterId                string                                            `json:"seriesMasterId,omitempty"`
	ShowAs                        interface{}                                       `json:"showAs,omitempty"`
	Start                         interface{}                                       `json:"start,omitempty"`
	Subject                       string                                            `json:"subject,omitempty"`
	TransactionId                 string                                            `json:"transactionId,omitempty"`
	Type                          interface{}                                       `json:"type,omitempty"`
	WebLink                       string                                            `json:"webLink,omitempty"`
	Attachments                   []MicrosoftGraphAttachment                        `json:"attachments,omitempty"`
	Calendar                      interface{}                                       `json:"calendar,omitempty"`
	Extensions                    []MicrosoftGraphExtension                         `json:"extensions,omitempty"`
	Instances                     []MicrosoftGraphEvent                             `json:"instances,omitempty"`
	MultiValueExtendedProperties  []MicrosoftGraphMultiValueLegacyExtendedProperty  `json:"multiValueExtendedProperties,omitempty"`
	SingleValueExtendedProperties []MicrosoftGraphSingleValueLegacyExtendedProperty `json:"singleValueExtendedProperties,omitempty"`
}
