/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1349 struct for InlineObject1349
type InlineObject1349 struct {
	Percent int32 `json:"percent,omitempty"`
}
