/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject940 struct for InlineObject940
type InlineObject940 struct {
	X          interface{} `json:"x,omitempty"`
	Alpha      interface{} `json:"alpha,omitempty"`
	Beta       interface{} `json:"beta,omitempty"`
	Cumulative interface{} `json:"cumulative,omitempty"`
	A          interface{} `json:"A,omitempty"`
	B          interface{} `json:"B,omitempty"`
}
