/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject791 struct for InlineObject791
type InlineObject791 struct {
	DestinationId string `json:"DestinationId,omitempty"`
}
