/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphOnenoteUserRole the model 'MicrosoftGraphOnenoteUserRole'
type MicrosoftGraphOnenoteUserRole string

// List of microsoft.graph.onenoteUserRole
const (
	MICROSOFTGRAPHONENOTEUSERROLE_OWNER       MicrosoftGraphOnenoteUserRole = "Owner"
	MICROSOFTGRAPHONENOTEUSERROLE_CONTRIBUTOR MicrosoftGraphOnenoteUserRole = "Contributor"
	MICROSOFTGRAPHONENOTEUSERROLE_NONE        MicrosoftGraphOnenoteUserRole = "None"
	MICROSOFTGRAPHONENOTEUSERROLE_READER      MicrosoftGraphOnenoteUserRole = "Reader"
)
