/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphDriveItemUploadableProperties struct for MicrosoftGraphDriveItemUploadableProperties
type MicrosoftGraphDriveItemUploadableProperties struct {
	Description    string      `json:"description,omitempty"`
	FileSize       int64       `json:"fileSize,omitempty"`
	FileSystemInfo interface{} `json:"fileSystemInfo,omitempty"`
	Name           string      `json:"name,omitempty"`
}
