/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject135 struct for InlineObject135
type InlineObject135 struct {
	SendResponse bool   `json:"SendResponse,omitempty"`
	Comment      string `json:"Comment,omitempty"`
}
