/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphConditionalAccessLocations struct for MicrosoftGraphConditionalAccessLocations
type MicrosoftGraphConditionalAccessLocations struct {
	ExcludeLocations []string `json:"excludeLocations,omitempty"`
	IncludeLocations []string `json:"includeLocations,omitempty"`
}
