/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphMailFolder struct for MicrosoftGraphMailFolder
type MicrosoftGraphMailFolder struct {
	Id                            string                                            `json:"id,omitempty"`
	ChildFolderCount              int32                                             `json:"childFolderCount,omitempty"`
	DisplayName                   string                                            `json:"displayName,omitempty"`
	ParentFolderId                string                                            `json:"parentFolderId,omitempty"`
	TotalItemCount                int32                                             `json:"totalItemCount,omitempty"`
	UnreadItemCount               int32                                             `json:"unreadItemCount,omitempty"`
	ChildFolders                  []MicrosoftGraphMailFolder                        `json:"childFolders,omitempty"`
	MessageRules                  []MicrosoftGraphMessageRule                       `json:"messageRules,omitempty"`
	Messages                      []MicrosoftGraphMessage                           `json:"messages,omitempty"`
	MultiValueExtendedProperties  []MicrosoftGraphMultiValueLegacyExtendedProperty  `json:"multiValueExtendedProperties,omitempty"`
	SingleValueExtendedProperties []MicrosoftGraphSingleValueLegacyExtendedProperty `json:"singleValueExtendedProperties,omitempty"`
}
