/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject995 struct for InlineObject995
type InlineObject995 struct {
	StartDate interface{} `json:"startDate,omitempty"`
	EndDate   interface{} `json:"endDate,omitempty"`
	Method    interface{} `json:"method,omitempty"`
}
