/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphInsightIdentity struct for MicrosoftGraphInsightIdentity
type MicrosoftGraphInsightIdentity struct {
	Address     string `json:"address,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	Id          string `json:"id,omitempty"`
}
