/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

import (
	"time"
)

// TimeOffRequest struct for TimeOffRequest
type TimeOffRequest struct {
	EndDateTime     time.Time `json:"endDateTime,omitempty"`
	StartDateTime   time.Time `json:"startDateTime,omitempty"`
	TimeOffReasonId string    `json:"timeOffReasonId,omitempty"`
}
