/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// TeamsAppInstallation struct for TeamsAppInstallation
type TeamsAppInstallation struct {
	TeamsApp           interface{} `json:"teamsApp,omitempty"`
	TeamsAppDefinition interface{} `json:"teamsAppDefinition,omitempty"`
}
