/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject831 struct for InlineObject831
type InlineObject831 struct {
	Commands []interface{} `json:"commands,omitempty"`
}
