/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphDelegateMeetingMessageDeliveryOptions the model 'MicrosoftGraphDelegateMeetingMessageDeliveryOptions'
type MicrosoftGraphDelegateMeetingMessageDeliveryOptions string

// List of microsoft.graph.delegateMeetingMessageDeliveryOptions
const (
	MICROSOFTGRAPHDELEGATEMEETINGMESSAGEDELIVERYOPTIONS_SEND_TO_DELEGATE_AND_INFORMATION_TO_PRINCIPAL MicrosoftGraphDelegateMeetingMessageDeliveryOptions = "sendToDelegateAndInformationToPrincipal"
	MICROSOFTGRAPHDELEGATEMEETINGMESSAGEDELIVERYOPTIONS_SEND_TO_DELEGATE_AND_PRINCIPAL                MicrosoftGraphDelegateMeetingMessageDeliveryOptions = "sendToDelegateAndPrincipal"
	MICROSOFTGRAPHDELEGATEMEETINGMESSAGEDELIVERYOPTIONS_SEND_TO_DELEGATE_ONLY                         MicrosoftGraphDelegateMeetingMessageDeliveryOptions = "sendToDelegateOnly"
)
