/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphConditionalAccessUsers struct for MicrosoftGraphConditionalAccessUsers
type MicrosoftGraphConditionalAccessUsers struct {
	ExcludeGroups []string `json:"excludeGroups,omitempty"`
	ExcludeRoles  []string `json:"excludeRoles,omitempty"`
	ExcludeUsers  []string `json:"excludeUsers,omitempty"`
	IncludeGroups []string `json:"includeGroups,omitempty"`
	IncludeRoles  []string `json:"includeRoles,omitempty"`
	IncludeUsers  []string `json:"includeUsers,omitempty"`
}
