/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// CollectionOfUserScopeTeamsAppInstallation struct for CollectionOfUserScopeTeamsAppInstallation
type CollectionOfUserScopeTeamsAppInstallation struct {
	Value []MicrosoftGraphUserScopeTeamsAppInstallation `json:"value,omitempty"`
}
