/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject395 struct for InlineObject395
type InlineObject395 struct {
	Message interface{} `json:"Message,omitempty"`
	Comment string      `json:"Comment,omitempty"`
}
