/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphPersistentBrowserSessionControl struct for MicrosoftGraphPersistentBrowserSessionControl
type MicrosoftGraphPersistentBrowserSessionControl struct {
	IsEnabled bool        `json:"isEnabled,omitempty"`
	Mode      interface{} `json:"mode,omitempty"`
}
