/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// CollectionOfWorkbookOperation struct for CollectionOfWorkbookOperation
type CollectionOfWorkbookOperation struct {
	Value []MicrosoftGraphWorkbookOperation `json:"value,omitempty"`
}
