/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1269 struct for InlineObject1269
type InlineObject1269 struct {
	Array interface{} `json:"array,omitempty"`
	X     interface{} `json:"x,omitempty"`
	Sigma interface{} `json:"sigma,omitempty"`
}
