/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// PlannerBucketTaskBoardTaskFormat struct for PlannerBucketTaskBoardTaskFormat
type PlannerBucketTaskBoardTaskFormat struct {
	OrderHint string `json:"orderHint,omitempty"`
}
