/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1203 struct for InlineObject1203
type InlineObject1203 struct {
	X            interface{} `json:"x,omitempty"`
	N            interface{} `json:"n,omitempty"`
	M            interface{} `json:"m,omitempty"`
	Coefficients interface{} `json:"coefficients,omitempty"`
}
