/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphCallDirection the model 'MicrosoftGraphCallDirection'
type MicrosoftGraphCallDirection string

// List of microsoft.graph.callDirection
const (
	MICROSOFTGRAPHCALLDIRECTION_INCOMING MicrosoftGraphCallDirection = "incoming"
	MICROSOFTGRAPHCALLDIRECTION_OUTGOING MicrosoftGraphCallDirection = "outgoing"
)
