/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject906 struct for InlineObject906
type InlineObject906 struct {
	Page string      `json:"page,omitempty"`
	Zoom interface{} `json:"zoom,omitempty"`
}
