/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphMailTipsType the model 'MicrosoftGraphMailTipsType'
type MicrosoftGraphMailTipsType string

// List of microsoft.graph.mailTipsType
const (
	MICROSOFTGRAPHMAILTIPSTYPE_AUTOMATIC_REPLIES     MicrosoftGraphMailTipsType = "automaticReplies"
	MICROSOFTGRAPHMAILTIPSTYPE_MAILBOX_FULL_STATUS   MicrosoftGraphMailTipsType = "mailboxFullStatus"
	MICROSOFTGRAPHMAILTIPSTYPE_CUSTOM_MAIL_TIP       MicrosoftGraphMailTipsType = "customMailTip"
	MICROSOFTGRAPHMAILTIPSTYPE_EXTERNAL_MEMBER_COUNT MicrosoftGraphMailTipsType = "externalMemberCount"
	MICROSOFTGRAPHMAILTIPSTYPE_TOTAL_MEMBER_COUNT    MicrosoftGraphMailTipsType = "totalMemberCount"
	MICROSOFTGRAPHMAILTIPSTYPE_MAX_MESSAGE_SIZE      MicrosoftGraphMailTipsType = "maxMessageSize"
	MICROSOFTGRAPHMAILTIPSTYPE_DELIVERY_RESTRICTION  MicrosoftGraphMailTipsType = "deliveryRestriction"
	MICROSOFTGRAPHMAILTIPSTYPE_MODERATION_STATUS     MicrosoftGraphMailTipsType = "moderationStatus"
	MICROSOFTGRAPHMAILTIPSTYPE_RECIPIENT_SCOPE       MicrosoftGraphMailTipsType = "recipientScope"
	MICROSOFTGRAPHMAILTIPSTYPE_RECIPIENT_SUGGESTIONS MicrosoftGraphMailTipsType = "recipientSuggestions"
)
