/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject66 struct for InlineObject66
type InlineObject66 struct {
	NewReminderTime MicrosoftGraphDateTimeTimeZone `json:"NewReminderTime,omitempty"`
}
