/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

import (
	"time"
)

// Segment struct for Segment
type Segment struct {
	Callee        interface{}   `json:"callee,omitempty"`
	Caller        interface{}   `json:"caller,omitempty"`
	EndDateTime   time.Time     `json:"endDateTime,omitempty"`
	FailureInfo   interface{}   `json:"failureInfo,omitempty"`
	Media         []interface{} `json:"media,omitempty"`
	StartDateTime time.Time     `json:"startDateTime,omitempty"`
}
