/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1184 struct for InlineObject1184
type InlineObject1184 struct {
	Bottom interface{} `json:"bottom,omitempty"`
	Top    interface{} `json:"top,omitempty"`
}
