/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1345 struct for InlineObject1345
type InlineObject1345 struct {
	Criteria string `json:"criteria,omitempty"`
}
