/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// MicrosoftGraphSecurity struct for MicrosoftGraphSecurity
type MicrosoftGraphSecurity struct {
	Id                         string                                    `json:"id,omitempty"`
	Alerts                     []MicrosoftGraphAlert                     `json:"alerts,omitempty"`
	SecureScoreControlProfiles []MicrosoftGraphSecureScoreControlProfile `json:"secureScoreControlProfiles,omitempty"`
	SecureScores               []MicrosoftGraphSecureScore               `json:"secureScores,omitempty"`
}
