/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

import (
	"time"
)

// MicrosoftGraphChatMessage struct for MicrosoftGraphChatMessage
type MicrosoftGraphChatMessage struct {
	Id                   string                                   `json:"id,omitempty"`
	Attachments          []interface{}                            `json:"attachments,omitempty"`
	Body                 MicrosoftGraphItemBody                   `json:"body,omitempty"`
	CreatedDateTime      time.Time                                `json:"createdDateTime,omitempty"`
	DeletedDateTime      time.Time                                `json:"deletedDateTime,omitempty"`
	Etag                 string                                   `json:"etag,omitempty"`
	From                 interface{}                              `json:"from,omitempty"`
	Importance           interface{}                              `json:"importance,omitempty"`
	LastEditedDateTime   time.Time                                `json:"lastEditedDateTime,omitempty"`
	LastModifiedDateTime time.Time                                `json:"lastModifiedDateTime,omitempty"`
	Locale               string                                   `json:"locale,omitempty"`
	Mentions             []interface{}                            `json:"mentions,omitempty"`
	MessageType          interface{}                              `json:"messageType,omitempty"`
	PolicyViolation      interface{}                              `json:"policyViolation,omitempty"`
	Reactions            []interface{}                            `json:"reactions,omitempty"`
	ReplyToId            string                                   `json:"replyToId,omitempty"`
	Subject              string                                   `json:"subject,omitempty"`
	Summary              string                                   `json:"summary,omitempty"`
	WebUrl               string                                   `json:"webUrl,omitempty"`
	HostedContents       []MicrosoftGraphChatMessageHostedContent `json:"hostedContents,omitempty"`
	Replies              []MicrosoftGraphChatMessage              `json:"replies,omitempty"`
}
