/*
 * Partial Graph API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package msgraph

// InlineObject1212 struct for InlineObject1212
type InlineObject1212 struct {
	Array interface{} `json:"array,omitempty"`
	K     interface{} `json:"k,omitempty"`
}
